export const SET_TOKEN = 'AUTH::SET_TOKEN';
export const SIGN_IN = 'AUTH::SIGN_IN';
export const SIGN_OUT = 'AUTH::SIGN_OUT';
export const SIGNED_OUT = 'AUTH::SIGNED_OUT';
export const SET_PROFILE = 'AUTH::SET_PROFILE';
export const ACTIVATE_REQUEST = 'AUTH::ACTIVATE_REQUEST';
export const ACTIVATE_SUCCESS = 'AUTH::ACTIVATE_SUCCESS';
export const ACTIVATE_FAILURE = 'AUTH::ACTIVATE_FAILURE';
