export const UPDATE = 'PROFILE::UPDATE';
export const RECEIVE_PROFILE = 'PROFILE::RECEIVE_PROFILE';
export const RECEIVE_MATCHES = 'PROFILE::RECEIVE_MATCHES';
export const SET_TEAMS = 'PROFILE::SET_TEAMS';
